# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20171012_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(default='', max_length=11),
        ),
    ]
